runtime: nodejs18
instance_class: F2
entrypoint: npm start
env: standard

handlers:
  # Serve static assets like images, CSS, and JavaScript
  - url: /static
    static_dir: static

  # Redirect all other requests to the app's main entry point
  - url: /.*
    script: auto
