runtime: nodejs18
env: standard
instance_class: F2
entrypoint: npm start

handlers:
  # Serve static assets (e.g., CSS, JS, and images)
  - url: /_next/static
    static_dir: .next/static

  - url: /static
    static_dir: static

  # Serve all other requests through the Next.js server
  - url: /.*
    script: auto
