steps:
  # Step 1: Use Node.js 18.18.0 image
  - name: "node:18.18.0"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        # Install dependencies
        npm install
        # Build the Next.js app
        npm run build

  # Step 2: Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet']

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  timeout: '1200s'  # 20 minutes
